apiVersion: v1
kind: Service
metadata:
  name: test-task
  labels:
    app: test-task
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app: test-task
